### ISSUE TITLE
Consider renaming World to JitterWorld or PhysicsWorld

### ISSUE THREAD

**Issue by Lurler** [notgiven688/jitterphysics2#131]
Good day.

The word `World` is pretty standard way to call your actual game world or a namespace in a project, so I think it would be a good idea to consider renaming `World` to `JitterWorld`, `JWorld` or `PhysicsWorld` or something similar to avoid collisions.

**Comment by notgiven688** [comment]
I get your point. Two reasons against a change:

1) This would unfortunately break the API.
2) This is what namespaces are for. The Vector/Matrix/Math struct are an exception, since these types are close to guaranteed to exist somewhere else in the project and are used all over the place.

Since the Jitter2-namespace itself does only house very few elements

![image](https://github.com/notgiven688/jitterphysics2/assets/37874600/89782605-906d-418b-9278-d2e2f9f641f0)

there might be the option for you to just remove "using Jitter2;" and add "using JWorld = Jitter2.World;" to get the desired outcome?

**Comment by Lurler** [comment]
Yeah, it's not a big deal, just small inconvenience. And yes, I myself also added using-renaming as you suggested.
