### ISSUE TITLE
How to create a convex hull from a model? 

### ISSUE THREAD

**Issue by CeSun** [notgiven688/jitterphysics2#23]
There is JConvexHull.Build function in jitterphysics1 that can do it. How should it be done in jitterphysics2?

**Comment by notgiven688** [comment]
Since the helper code is independent from the engine (with the exception of the `JVector` struct), I recommend that you directly incorporate the following into your code:

https://github.com/notgiven688/jitterphysics/blob/master/source/Jitter/LinearMath/JConvexHull.cs

The aforementioned code returns an array of indices representing the points that form the convex hull when given a point cloud as input. In Jitter2, you can then use these resultant points with the `PointCloudShape`. If your convex hull consists of more than roughly 30 points, it would be more appropriate to switch to the `ConvexHullShape`. This shape requires a triangle mesh as input and proves to be more efficient for larger meshes. For crafting the necessary input shapes, consider utilizing modeling programs like Blender. Specifically, in Blender's Edit mode, Mesh -> Convex Hull.

The whole topic needs documentation. I admit.
