### ISSUE TITLE
Rigid Body damping is reversed

### ISSUE THREAD

**Issue by RonenNess** [notgiven688/jitterphysics2#54]
Hello,

Aside for this issue #53 , the damping values themselves are also seems to be reversed.

This means that damping value of 0 completely stop the objects from moving (what should happen with damping value of 1) while damping value of 1 actually let the objects move forever (what should happen with 0).

In other words, I need to set damping like this in order for it to behave like in other physics simulators:

```cs
rigidBody.Damping = (1f - actualLinearDamping, 1f - actualAngularDamping);
```

Is that intentional? I checked with few other engines and there seems to be a consensus that 0 = no damping, 1 = 100% damping, and sometimes negative value increase movement.

Thanks!

**Comment by notgiven688** [comment]
Hello!

Interesting point. This was intentional - the documentation-tag says:
"Specifies the damping factors. The angular and linear velocities are multiplied by these values at each step. "

Applying this rule results in a "damped" movement of the (free) body `x(t)=A*exp(-lambda*t)`, where lambda is given by (1-jitters_damping_factor). One could argue that lambda is the more natural choice for "Damping".

I will think about reversing the definition as you suggested.

**Comment by notgiven688** [comment]
Fixed the reversal.
