### ISSUE TITLE
Rigid Body with Mass of 0 cause NaN in velocity and position.

### ISSUE THREAD

**Issue by RonenNess** [notgiven688/jitterphysics2#55]
Usually Mass = 0 means static objects.
If Mass of zero is not supported, its best to throw exception immediately upon setting it.
But IMO its better to support it and not generate NaNs.

**Comment by notgiven688** [comment]
> Usually Mass = 0 means static objects.

Is this the case, actually? Just by the formulas it makes sense that setting the mass to infinity creates static bodies, since

a=F/m 

goes to zero as the mass approaches infinity.

This is (partly) supported by Jitter and is one way to create "kinetic" objects. Nevertheless we now check for zero mass in SetMassInertia, https://github.com/notgiven688/jitterphysics2/pull/62.
